import re

with open('src/data/mockEvents.ts', 'r', encoding='utf-8') as f:
    content = f.read()

new_events = """  ,
  {
    id: 'school-1',
    title: 'Galatasaray Futbol Okulu (Florya)',
    slug: 'gs-futbol-okulu-florya',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Florya Metin Oktay Tesisleri',
    date: 'Tüm Yıl',
    organizer: 'Galatasaray SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1574629810360-7efbb928ac05?q=80&w=1200&auto=format&fit=crop',
    description: 'Galatasaray Futbol Okulu, geleceğin yıldızlarını yetiştiriyor. Uzman antrenörler eşliğinde profesyonel futbol eğitimi.',
    overallScore: 9.1,
    ratingBreakdown: { antrenor: 9.5, tesis: 9.0, hijyen: 8.5 },
    reviewCount: 120,
    featured: true,
    isActive: true,
    tags: ['Futbol', 'Altyapı', 'Çocuk Sporu'],
    reviews: []
  },
  {
    id: 'school-2',
    title: 'Fenerbahçe Spor Okulları (Dereağzı)',
    slug: 'fb-spor-okullari-dereagzi',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Dereağzı Lefter Küçükandonyadis Tesisleri',
    date: 'Tüm Yıl',
    organizer: 'Fenerbahçe SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=1200&auto=format&fit=crop',
    description: 'Fenerbahçe Spor Okulları, basketbol, voleybol ve futbol branşlarında genç yeteneklere eğitim veriyor.',
    overallScore: 8.9,
    ratingBreakdown: { antrenor: 9.2, tesis: 8.8, hijyen: 8.6 },
    reviewCount: 95,
    featured: false,
    isActive: true,
    tags: ['Basketbol', 'Voleybol', 'Futbol'],
    reviews: []
  },
  {
    id: 'school-3',
    title: 'Beşiktaş Basketbol Okulu (Akatlar)',
    slug: 'bjk-basketbol-okulu-akatlar',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Akatlar Spor Kompleksi',
    date: 'Tüm Yıl',
    organizer: 'Beşiktaş JK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?q=80&w=1200&auto=format&fit=crop',
    description: 'Beşiktaş Basketbol Okulu ile çocuklar basketbolun temel becerilerini profesyonel şartlarda öğreniyor.',
    overallScore: 8.7,
    ratingBreakdown: { antrenor: 8.9, tesis: 8.5, hijyen: 8.7 },
    reviewCount: 82,
    featured: false,
    isActive: true,
    tags: ['Basketbol', 'Altyapı'],
    reviews: []
  },
  {
    id: 'school-4',
    title: 'Eczacıbaşı Voleybol Okulu',
    slug: 'eczacibasi-voleybol-okulu',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Ayazağa Spor Salonu',
    date: 'Tüm Yıl',
    organizer: 'Eczacıbaşı Spor Kulübü',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1593786477114-61cbf51bf18b?q=80&w=1200&auto=format&fit=crop',
    description: 'Türkiye\'nin köklü voleybol kulübü Eczacıbaşı, geleceğin yıldız kız voleybolcularını arıyor.',
    overallScore: 9.5,
    ratingBreakdown: { antrenor: 9.8, tesis: 9.2, hijyen: 9.5 },
    reviewCount: 210,
    featured: true,
    isActive: true,
    tags: ['Voleybol', 'Kız Sporu', 'Profesyonel'],
    reviews: []
  },
  {
    id: 'school-5',
    title: 'Darüşşafaka Basketbol Altyapı',
    slug: 'darussafaka-basketbol-altyapi',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Darüşşafaka Ayhan Şahenk Spor Salonu',
    date: 'Tüm Yıl',
    organizer: 'Darüşşafaka SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1627627256672-027a4613d028?q=80&w=1200&auto=format&fit=crop',
    description: 'Türk basketbolunun köklü altyapısı Darüşşafaka\'da elit düzeyde eğitim imkanı.',
    overallScore: 9.0,
    ratingBreakdown: { antrenor: 9.4, tesis: 8.7, hijyen: 8.9 },
    reviewCount: 150,
    featured: false,
    isActive: true,
    tags: ['Basketbol', 'Altyapı'],
    reviews: []
  },
  {
    id: 'school-6',
    title: 'VakıfBank Voleybol Okulu (Üsküdar)',
    slug: 'vakifbank-voleybol-okulu-uskudar',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'VakıfBank Spor Sarayı',
    date: 'Tüm Yıl',
    organizer: 'VakıfBank SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?q=80&w=1200&auto=format&fit=crop',
    description: 'Dünya şampiyonu VakıfBank\'ın altyapısında voleybol kariyerine adım atın.',
    overallScore: 9.4,
    ratingBreakdown: { antrenor: 9.7, tesis: 9.5, hijyen: 9.1 },
    reviewCount: 300,
    featured: true,
    isActive: true,
    tags: ['Voleybol', 'Profesyonel', 'Avrupa Yakası'],
    reviews: []
  },
  {
    id: 'school-7',
    title: 'ENKA Tenis Okulu (İstinye)',
    slug: 'enka-tenis-okulu-istinye',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'ENKA Sadi Gülçelik Spor Sitesi',
    date: 'Tüm Yıl',
    organizer: 'ENKA Spor Kulübü',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1200&auto=format&fit=crop',
    description: 'Dünya standartlarında kortlarda, milli antrenörler eşliğinde profesyonel tenis eğitimi.',
    overallScore: 9.3,
    ratingBreakdown: { antrenor: 9.1, tesis: 9.8, hijyen: 9.2 },
    reviewCount: 115,
    featured: false,
    isActive: true,
    tags: ['Tenis', 'Raket Sporları', 'Bireysel Sporlar'],
    reviews: []
  },
  {
    id: 'school-8',
    title: 'TED Ankara Kolejliler Basketbol Okulu',
    slug: 'ted-ankara-kolejliler-basketbol',
    category: 'Spor Okulları',
    city: 'Ankara',
    venue: 'TED Ankara Koleji Spor Salonu',
    date: 'Tüm Yıl',
    organizer: 'TED Ankara Kolejliler',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1505666287802-931dc83948e9?q=80&w=1200&auto=format&fit=crop',
    description: 'Ankara\'nın en saygın basketbol okullarından birinde spora başlama şansı.',
    overallScore: 8.8,
    ratingBreakdown: { antrenor: 9.0, tesis: 8.5, hijyen: 8.8 },
    reviewCount: 140,
    featured: true,
    isActive: true,
    tags: ['Basketbol', 'Ankara', 'Okul Sporları'],
    reviews: []
  },
  {
    id: 'school-9',
    title: 'Karşıyaka Yelken ve Su Sporları Okulu',
    slug: 'karsiyaka-yelken-ve-su-sporlari',
    category: 'Spor Okulları',
    city: 'İzmir',
    venue: 'Karşıyaka Yelken Kulübü',
    date: 'Yaz Dönemi',
    organizer: 'Karşıyaka Spor Kulübü',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1533140938495-9ff27e1b9b94?q=80&w=1200&auto=format&fit=crop',
    description: 'Denizi ve rüzgarı sevenler için optimist ve yelken eğitimleri.',
    overallScore: 9.2,
    ratingBreakdown: { antrenor: 9.3, tesis: 8.8, hijyen: 9.5 },
    reviewCount: 75,
    featured: false,
    isActive: true,
    tags: ['Yelken', 'Su Sporları', 'İzmir'],
    reviews: []
  },
  {
    id: 'school-10',
    title: 'Göztepe Cimnastik Okulu',
    slug: 'goztepe-cimnastik-okulu',
    category: 'Spor Okulları',
    city: 'İzmir',
    venue: 'Gürsel Aksel Tesisleri',
    date: 'Tüm Yıl',
    organizer: 'Göztepe SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1579213166547-5a1e74f44fa6?q=80&w=1200&auto=format&fit=crop',
    description: 'Çocukların fiziksel gelişimine katkıda bulunan temel cimnastik eğitimleri.',
    overallScore: 8.6,
    ratingBreakdown: { antrenor: 8.9, tesis: 8.2, hijyen: 8.6 },
    reviewCount: 90,
    featured: false,
    isActive: true,
    tags: ['Cimnastik', 'Temel Spor', 'Çocuk Gelişimi'],
    reviews: []
  },
  {
    id: 'event-rep-1',
    title: 'Boğaziçi Kıtalararası Yüzme Yarışı 2026',
    slug: 'bogazici-yuzme-yarisi-2026',
    category: 'Spor Etkinlikleri',
    city: 'İstanbul',
    venue: 'İstanbul Boğazı (Kanlıca-Kuruçeşme)',
    date: '23 Ağustos 2026',
    organizer: 'Türkiye Milli Olimpiyat Komitesi',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1519315901367-f34f828a2a7a?q=80&w=1200&auto=format&fit=crop',
    description: 'Dünyanın en iyi açık su yüzme organizasyonlarından biri. İki kıta arası yüzme heyecanı.',
    overallScore: 9.8,
    ratingBreakdown: { organizasyonAkis: 9.7, parkurGuvenlik: 9.9, atmosferSeyir: 10.0 },
    reviewCount: 520,
    featured: true,
    isActive: true,
    tags: ['Yüzme', 'Açık Su', 'Uluslararası'],
    reviews: []
  },
  {
    id: 'event-rep-2',
    title: 'Kapadokya Ultra Trail 2026',
    slug: 'kapadokya-ultra-trail-2026',
    category: 'Spor Etkinlikleri',
    city: 'Nevşehir',
    venue: 'Ürgüp Şehir Merkezi',
    date: '17 Ekim 2026',
    organizer: 'Argeus Events',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1605335626244-933e496a7ce9?q=80&w=1200&auto=format&fit=crop',
    description: 'Peribacalarının arasında gerçekleşen, dünyanın dört bir yanından sporcuları ağırlayan ultra maraton.',
    overallScore: 9.7,
    ratingBreakdown: { organizasyonAkis: 9.6, parkurGuvenlik: 9.5, kitIkram: 9.8 },
    reviewCount: 380,
    featured: true,
    isActive: true,
    tags: ['Koşu', 'Ultra Maraton', 'Doğa Sporları'],
    reviews: []
  },
  {
    id: 'event-rep-3',
    title: 'İstanbul Yarı Maratonu 2026',
    slug: 'istanbul-yari-maratonu-2026',
    category: 'Spor Etkinlikleri',
    city: 'İstanbul',
    venue: 'Tarihi Yarımada',
    date: '5 Nisan 2026',
    organizer: 'Spor İstanbul',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=1200&auto=format&fit=crop',
    description: 'Dünyanın en hızlı yarı maraton parkurlarından birinde kıyasıya mücadele ve tarihi manzara.',
    overallScore: 9.2,
    ratingBreakdown: { organizasyonAkis: 9.0, parkurGuvenlik: 9.4, atmosferSeyir: 9.5 },
    reviewCount: 415,
    featured: false,
    isActive: true,
    tags: ['Koşu', 'Yarı Maraton', 'Atletizm'],
    reviews: []
  }
"""

# Find the end of INITIAL_EVENTS array
match = re.search(r'export const INITIAL_EVENTS: SportsEvent\[\] = \[.*?\];', content, flags=re.DOTALL)
if match:
    full_array = match.group(0)
    # inject just before the last "];"
    new_array = full_array[:-2] + new_events + full_array[-2:]
    content = content.replace(full_array, new_array)
    
    with open('src/data/mockEvents.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Injected new events successfully")
else:
    print("Could not find INITIAL_EVENTS array")
